services:
  9router:
    build: .
    container_name: 9router
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "20128:20128"
    volumes:
      - /home/ubuntu/.9router:/root/.9router
    networks:
      - web

networks:
  web:
    name: web
    external: true
