services:
  9router:
    build: .
    container_name: 9router
    restart: unless-stopped
    network_mode: "host"
    tty: true
    stdin_open: true
    volumes:
      - /home/ubuntu/.9router:/root/.9router
